### ISSUE TITLE
Strange bid in B1 of demo boards - I did not find any reason for it in the training data

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#103]
Hi,

I looked at board 1 and I think the 1NT bid is strange - why wouldn't you pass instead? You have five pretty good clubs.
So I looked into bidding_data.txt and search for
"X XX P 1N" - zero hits
"X XX P P" - 308 hits

Are we ignoring doubles and redoubles in the learning process?
Otherwise I don't understand BENs bidding.

@ThorvaldAagaard thanks for updating the demo site.

![image](https://github.com/lorserker/ben/assets/33804161/6a21bea2-9fa3-45bf-9b76-a6f6fa85fcb9)

**Comment by ThorvaldAagaard** [comment]
Bidding_data.txt is old, and not used for the current models.

Most training is based on BBA https://sites.google.com/view/bbaenglish and BBA is having some difficulties handling bidding after XX

**Comment by ThorvaldAagaard** [comment]
You can find the data used for training BEN with the models used to play the Camrose Deals on the demo site here: https://netbridge.dk/bridge/Upload/SAYC-Version%207918.zip
