### ISSUE TITLE
Bug in B11 of the demo - miscounting tricks

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#105]
N cashes the last trick but it's counted for the opponents.

![image](https://github.com/lorserker/ben/assets/33804161/aabd9ef5-d4c8-494d-abde-905dd9b76153)
![image](https://github.com/lorserker/ben/assets/33804161/03a9fbe8-7797-4843-8c4c-12f88c0025f1)

**Comment by ThePokerDude** [comment]
Sorry - 1st screenshot is wrong - here the correct one

![image](https://github.com/lorserker/ben/assets/33804161/8abd2472-fd17-422e-9eb9-a1637409634c)

**Comment by ThorvaldAagaard** [comment]
This is fixed now
