### ISSUE TITLE
really bad bidding in B38

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#109]
Obviously 1NT is a beginner mistake - it shows 12-14. BEN should have bid 2NT to show 18-19.
I found about 8000 boards with 1m P 1M P 2N in the bidding_data.txt.
I have no idea how BEN could make such a mistake.

![image](https://github.com/lorserker/ben/assets/33804161/3452cc55-0771-4f5b-bca6-3314377c67d1)

**Comment by ThorvaldAagaard** [comment]
Yes, this is very strange

**Comment by ThorvaldAagaard** [comment]
This was found in the training data, but I was not able to recreate how they was produced, So hopefully it will be gone next time I train the models

**Comment by ThorvaldAagaard** [comment]
Latest BBA
![image](https://github.com/user-attachments/assets/53246963-5093-47c2-a6d4-dce3224d9dee)
Latest trained model
![image](https://github.com/user-attachments/assets/207bfd4f-a1a7-4cb6-ae43-4e9036a4cb14)
