### ISSUE TITLE
Making a test run

### ISSUE THREAD

**Issue by ThorvaldAagaard** [lorserker/ben#11]
I am trying 

https://github.com/lorserker/ben/tree/main/scripts/training/bidding#making-a-test-run

but it looks like the reference to the model in this line

python testrun.py bidding/bidding-1000000 < test_input.txt

isn't correct

Shouldn't it be model/bidding-1000000 ?

But how to debug, when the bidding is not like expected?

**Comment by lorserker** [comment]
yes, the model reference should point to a model you trained.

how to debug is not clear.
you can see it more line a unit test, to check how many of the test hands it can bid as expected.
then you would add more training examples for sequences it doesn't know yet, re-train and then run the test again to see if now it knows how to bid it and hasn't forgotten something else it knew before

**Comment by ThorvaldAagaard** [comment]
I was just following the tutorial from the top, and normally you place the model in directory ```model```

About debugging I understand it really isn't possible, and if getting bad results it is probably either to few input, or to few iterations. 

In my first sample I was just me misreading the output :-)

**Comment by lorserker** [comment]
i have edited the path in the readme
