### ISSUE TITLE
indredibly bad lead - demo B42

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#110]
C4 is not a real option

![image](https://github.com/lorserker/ben/assets/33804161/ee099023-35db-42f3-94c6-a1da2be4d6f0)

**Comment by ThorvaldAagaard** [comment]
I havent't looked at it, but look at the samples - they might tell why BEN selects that lead

**Comment by ThorvaldAagaard** [comment]
![image](https://github.com/lorserker/ben/assets/10560652/cb412827-e9b1-454c-970e-e9e0f4a02eb0)
Notice that small spade is recommended by the neural network.
We have only 10 samples and it looks like the result is the same leading a low club as leading the queen, so it ends up being the neural network.

This is a good example of why we need to follow common lead rules, but as it is on the plan I will close this.
