### ISSUE TITLE
misjudgement in the bidding B62

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#111]
S has shown maximum with 4h. N signs off with 4h. There is no reson to bid on.

![image](https://github.com/lorserker/ben/assets/33804161/6b24f4dd-6df3-49ef-814e-eca3dfad0ec3)

**Comment by ThorvaldAagaard** [comment]
Next training should bid the board like this
34C4296E0892B5C8D70933502FE3
![image](https://github.com/lorserker/ben/assets/10560652/5f79f009-b639-4406-87d2-d97eea8c0559)

**Comment by ThorvaldAagaard** [comment]
Latest BBA
![image](https://github.com/user-attachments/assets/63ffc8b4-c858-43d2-bfd8-39365a59ba5d)

Latest BEN
![image](https://github.com/user-attachments/assets/65caadeb-0eae-4df5-ad35-1df981cfde71)
