### ISSUE TITLE
BEN does not yet understand 4th suit forcing

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#112]
2S askes for stopper, so BEN should bid 3c. 3NT after 2S is a clear mistake.
2S is dubious (you do not really look for a club slam). Instead of 2S 3NT would be better.

![image](https://github.com/lorserker/ben/assets/33804161/2e18e522-ee07-4c94-9a69-c877fbd5a797)

**Comment by ThorvaldAagaard** [comment]
Agree
Created issue at BBA: https://github.com/EdwardPiwowar/BBA/issues/249
