### ISSUE TITLE
how does BEN iterpret 1c-P-1d-P-1h-P-1s demo B92?

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#113]
Hi 3nt seems wild to me. There is no system where 1s is gameforcing in this sequence?

![image](https://github.com/lorserker/ben/assets/33804161/29ff912e-f44a-43c7-9d0c-9a21d184553e)

**Comment by ThorvaldAagaard** [comment]
1S its 4th suit forcing but like you not like the preemptive jump to 3N
Reported to BBA at https://github.com/EdwardPiwowar/BBA/issues/248
