### ISSUE TITLE
misjudgement / blunder in B123

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#114]
Inviting with 13 HCP is wrong. South should pass at partner's 1NT.
![image](https://github.com/lorserker/ben/assets/33804161/4ab3a997-8853-4f9e-85fa-b0181dc9f7b5)

**Comment by ThorvaldAagaard** [comment]
Latest BBA
![image](https://github.com/user-attachments/assets/bb797809-46f8-4570-978a-0f63107f7b4e)
Latest BEN
![image](https://github.com/user-attachments/assets/4ea36749-b1e3-45d9-ba88-d59d15eacdb5)

So BEN no longer bids 2N, and I agree with 2H - hard to get to 3D
