### ISSUE TITLE
bad bidding in B125

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#115]
South has an obvious 3NT bid instead of 2c.
![image](https://github.com/lorserker/ben/assets/33804161/e15af51c-ad55-4686-9cb2-644205bd933b)

**Comment by ThorvaldAagaard** [comment]
Seems to be an error in the training data

**Comment by ThorvaldAagaard** [comment]
Latest version
![image](https://github.com/user-attachments/assets/9fd3e703-8043-48b5-a22f-c353bb558374)
