### ISSUE TITLE
Slight misjudgement in B126

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#116]
Instead of bidding 3NT N should pass for penalty.
North does not even consider passing.

Bid: 3N by Simulation
Candidates:
Bid: 3N, Expected score: 307, NN Score: 0.188, Adjusted: 9
Bid: 2N, Expected score: 147, NN Score: 0.114, Adjusted: 6
Bid: 3D, Expected score: 94, NN Score: 0.644, Adjusted: 32
![image](https://github.com/lorserker/ben/assets/33804161/f03fd414-620d-4dd0-8237-bb1338f145f8)

**Comment by ThorvaldAagaard** [comment]
Could be right - could be wrong.
This is from the actual matches
![image](https://github.com/lorserker/ben/assets/10560652/96fbe151-2a08-452d-b2d6-294ac07acf27)

**Comment by ThorvaldAagaard** [comment]
As this is reported as an error  at BBA, I will close this.
