### ISSUE TITLE
bad bidding in b130

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#117]
West should bid 3nt instead of 2s.
You want to play 3nt anyway. Why bother bidding 2s and giving the opponents the opportunity to ive a lead directing double.
![image](https://github.com/lorserker/ben/assets/33804161/8ed04d92-7b99-4134-9a8b-606c8894ed9b)

**Comment by ThorvaldAagaard** [comment]
Agree. It is a training issue.

**Comment by ThorvaldAagaard** [comment]
In latest version
![image](https://github.com/user-attachments/assets/cb876e67-1ebc-4c6b-9b64-2f14671c983c)
