### ISSUE TITLE
Strange 3S bid in b142

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#119]
What's 3s? Should be cuebid - but west has no spade cuebid.
![image](https://github.com/lorserker/ben/assets/33804161/b0e2cbc7-80f7-4d6f-a811-ce0b89d15a6f)

**Comment by ThorvaldAagaard** [comment]
Yes, but all 4 bids are almost equal.
![image](https://github.com/lorserker/ben/assets/10560652/2dd479b1-ecb8-4965-bcaa-94c62c40a946)

That is the cost of a neural network, and will require more training with this specific sequence

**Comment by ThorvaldAagaard** [comment]
In latest version East just bids 4H. Perhaps a bit optimistic
![image](https://github.com/user-attachments/assets/fe2ed904-a043-4751-922b-40502b4a2102)
And latest BBA
![image](https://github.com/user-attachments/assets/975f8349-6fbd-4c4e-9b8a-a62ebada90c5)
