### ISSUE TITLE
Question about sys.platform in PIMC.py

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#127]
now:

if sys.platform == 'win32':
    BGADLL_LIB = 'BGADLL'
elif sys.platform == 'darwin':
    BGADLL_LIB = 'N/A'
else:
    BGADLL_LIB = 'N/A'

could be replaced by:

if sys.platform == 'win32':
    BGADLL_LIB = 'BGADLL'
else:
    BGADLL_LIB = 'N/A'

Do you plan to implement something for darwin or specifically state that for darwin BGADLL_LIB = 'N/A' ?

**Comment by ThePokerDude** [comment]
*specifically state

**Comment by ThorvaldAagaard** [comment]
It is a copy from DDS, where we support Darwin. I don't think we will support PIMC on Darwin, but I left it as you never can know :-)
