### ISSUE TITLE
Ben misses spade fit in a strange way after 1nt opening

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#130]
Does Ben play simple stayman? If yes - what is 2nt? Does it show 5card major? If it shows 5card major you shouldn't miss the spade fit.
![image](https://github.com/lorserker/ben/assets/33804161/8eb5b687-27fa-4ec9-bec8-bd4f446f7cbc)

**Comment by ThePokerDude** [comment]
[Event ""]
[Site ""]
[Date ""]
[Board "114"]
[Dealer "E"]
[Vulnerable "NS"]
[Deal "E:QT732.J92.AK4.AJ J5.T53.T875.K432 K86.AQ64.QJ962.9 A94.K87.3.QT8765"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "E"]
[Contract "3NT"]
[Result "12"]
{PAR of the deal: 6S  = played by West: 980 points}
{PAR computation time: 00'01"}
{Feasability: 8 2 2 1 2 5 11 10 11 8 8 2 2 1 2 5 11 10 12 8 }
[Auction "E"]
1NT Pass 2C Pass
2NT Pass 3D Pass
3NT Pass Pass Pass
[Play "S"]
c4 C9 ct CJ
d7 D6 d3 DA
d5 D2 c5 DK
d8 DQ h8 D4
dt DJ s4 H2
ck D9 s9 H9
s5 S8 sa S7
c2 H6 cq CA
h3 HA h7 HJ
sj SK c6 S3
c3 S6 c7 SQ
h5 H4 c8 S2
ht HQ hk ST

**Comment by ThorvaldAagaard** [comment]
The EW bidding is for WBridge5, and not for BEN
It looks like Eamon placed BEN EW and should have placed BEN NS.
This is how BEN bids it with the current default

But probably worth looking at https://github.com/EdwardPiwowar/BBA/issues/269 
I will close this, but you are welcome to file a report to BBA about the strange WBridge5 bidding
