### ISSUE TITLE
Ben runs out of 1nt X unnecessarily in B117 of match240310-_WBridge5_v_ben0308p5dd.pbn

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#131]
Passing to 1ntX seems better to me thean 2c
![image](https://github.com/lorserker/ben/assets/33804161/7d29901e-ce1e-4248-bc80-cdd478ea74e5)

**Comment by ThePokerDude** [comment]
[Event ""]
[Site ""]
[Date ""]
[Board "117"]
[Dealer "E"]
[Vulnerable "EW"]
[Deal "E:A63.K6.653.AKQ87 Q5.A954.AKQ7.542 KJ9.8732.J94.T96 T8742.QJT.T82.J3"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
{PAR of the deal: 3H X -1 played by south: -100 pts}
{Feasability: 5 7 8 7 5 8 4 5 5 8 5 8 8 7 5 8 4 5 5 5
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "S"]
[Contract "3D"]
[Result "8"]
{PAR of the deal: 3H X -1 played by south: -100 pts}
{Feasability: 5 7 8 7 5 8 4 5 5 8 5 8 8 7 5 8 4 5 5 5}
[Auction "E"]
1NT X Pass Pass
2C Pass Pass 2S
Pass 3D Pass Pass
Pass 
[Play "W"]
H7 ht HK ha
H8 hj H6 h5
H3 hq D3 h9
C6 c3 CK c2
CT cj CA c4
D4 d2 D6 dk
C9 d8 C7 c5
D9 dt D5 da
DJ s2 S3 dq
H2 s4 C8 h4
S9 st SA s5
SJ s7 CQ d7
SK s8 S6 sq

**Comment by ThorvaldAagaard** [comment]
It is OK to run, as fixing this requires some handevaluation, that BBA doesn't have. Currently I have forced BBA not to run on balanced hands.

So we will do nothing with this.
