### ISSUE TITLE
Blunder in declarer play in B161

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#134]
After CQ lead north is marked with CJ. Finesse is obvious.
In trick 6 instead of CK Ben should play 8 or 9.
I think it is a good board to test improvements in game play
![image](https://github.com/lorserker/ben/assets/33804161/709e8cd9-38e2-4438-847b-fb083c878b29)

**Comment by ThePokerDude** [comment]
[Event ""]
[Site ""]
[Date ""]
[Board "161"]
[Dealer "E"]
[Vulnerable "None"]
[Deal "E:A73.K84.653.AK98 T954.QT72.AT72.3 QJ6.AJ965.K84.T5 K82.3.QJ9.QJ7642"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
{PAR of the deal: 5NT = played by east: 460 points}
{Feasability: 5 5 2 5 2 8 8 11 8 11 5 5 2 5 2 8 8 11 8 11
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "W"]
[Contract "4H"]
[Result "9"]
{PAR of the deal: 5NT = played by east: 460 points}
{Feasability: 5 5 2 5 2 8 8 11 8 11 5 5 2 5 2 8 8 11 8 11}
[Auction "E"]
1C Pass 1H Pass
1NT Pass 2C Pass
2D Pass 2H Pass
4H Pass Pass Pass
[Play "N"]
cq CA c3 CT
h3 H4 h7 HJ
c2 H8 h2 HA
s2 HK ht H6
sk S7 s5 SQ
c6 CK hq C5
d9 D6 d7 D8
s8 SA s4 S6
dj D5 d2 DK
c4 S3 s9 SJ
dq D3 dt D4
cj C8 da H5
c7 C9 st H9

**Comment by ThorvaldAagaard** [comment]
In current version BEN will lead a trump.
If I lead CQ BEN will take the finesse, but unfortunately not taking the finesse in heart, so going down.
Simulations look ok, so I will close this
