### ISSUE TITLE
Bad defence in B164

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#135]
When declarer play club by himself it looks natural to play heart after club Ace instead of C9.
![image](https://github.com/lorserker/ben/assets/33804161/0ddb1cda-c41b-43b9-8a92-ee9800eee492)

**Comment by ThePokerDude** [comment]
[Event ""]
[Site ""]
[Date ""]
[Board "164"]
[Dealer "N"]
[Vulnerable "All"]
[Deal "N:AQ92.A632.QJ.T75 863.J95.96543.A9 KJT.K4.K872.QJ64 754.QT87.AT.K832"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
{PAR of the deal: 3S  = played by south: 140 points}
{Feasability: 10 8 6 9 8 3 5 5 4 5 10 8 6 9 8 3 5 5 4 5
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "S"]
[Contract "3NT"]
[Result "10"]
{PAR of the deal: 3S  = played by south: 140 points}
{Feasability: 10 8 6 9 8 3 5 5 4 5 10 8 6 9 8 3 5 5 4 5}
[Auction "N"]
1C Pass 1D Pass
1H Pass 3NT Pass
Pass Pass 
[Play "W"]
S4 sq S3 st
S5 s2 S8 sk
C3 ct CA c4
CK c5 C9 cq
C8 c7 H5 cj
C2 h2 D6 c6
DA dj D5 d2
S7 s9 S6 sj
DT dq D4 d7
H7 h3 H9 hk
H8 h6 D9 dk
HT sa D3 d8
HQ ha HJ h4

**Comment by ThorvaldAagaard** [comment]
BEN is still far away form any reasoning like. when declarer plays the suit I might better play something else.

But if you have an idea of how to handle it, it would be nice - It is a very common problem among robots.

I will not do anything to fix this for now.
