### ISSUE TITLE
parse_lin(lin) function seems unable to parse .lin files with all 4 hands specified

### ISSUE THREAD

**Issue by thevava** [lorserker/ben#16]
Looks like the problem lies in this line:
https://github.com/lorserker/ben/blob/46fa30e2b6c8f810fae0cc6ff562008f981859d2/src/util.py#L91

The regex doesn't work when the .lin specifies 4 hands (instead of the usual 3 + final comma). E.g.
```
st||md|3S52H864DKJ75CKJ73,SQJ4HQ972DQ4CT942,SA963HATDA9832CQ5,SKT87HKJ53DT6CA86|rh||ah|Board 49|sv|o|mb|1D|mb|d|mb|2D|mb|2H|mb|3D|mb|3H|mb|p|mb|p|mb|p|pg||pc|CQ|pc|CA|pc|C3|pc|C2|pg||pc|HJ|pc|H4|pc|H2|pc|HA|pg||pc|C5|pc|C6|pc|CJ|pc|CT|pg||pc|DK|pc|D4|pc|D9|pc|D6|pg||pc|CK|pc|C4|pc|S3|pc|C8|pg||pc|D5|pc|DQ|pc|DA|pc|DT|pg||pc|SA|pc|S7|pc|S2|pc|S4|pg||pc|S6|pc|S8|pc|S5|pc|SQ|pg||pc|H7|pc|HT|pc|HK|mc|7|
```

**Comment by thevava** [comment]
This is the first time I open an issue or do anything to any repository which I don't own, so I apologize in advance if I'm showing a lack etiquette by proposing this right away: I wrote a regex that solves this (I used it for a lin parser I wrote some time ago):
```
(?<=md\|)(.*?)(?=\|)
```
Should I open a pull request or something like that?

**Comment by lorserker** [comment]
@thevava thanks for finding bugs and reporting them 👍 

i warmly encourage you to make a pull request if you like.

**Comment by thevava** [comment]
Thanks, I went ahead! It's a pleasure to help with such a wonderful project. Btw kudos for the engine: it's fantastic! Keep up the great work!
