### ISSUE TITLE
self trained model by following instruction not as good as gib21

### ISSUE THREAD

**Issue by ed2k** [lorserker/ben#22]
following https://github.com/lorserker/ben/tree/main/scripts/training/bidding
trained bidding-1000000
seems the result is not as good as gib21, what might be the reason

**Comment by Muppet1** [comment]
When did you do the training.  I can't get the trainer to act sensibly in the last 2 weeks.

**Comment by ed2k** [comment]
> When did you do the training. I can't get the trainer to act sensibly in the last 2 weeks.
1.5 week ago.
what issue do you see? are you able to run only the bidding inference part.

**Comment by Muppet1** [comment]
basically the training runs but the value printed is zero or very close to zero and the NN doesn't gain any information.

Even using the gib data that previously worked fine.

previous to that I trained the prec and the polish club and one of the other networks with no issue.

**Comment by ed2k** [comment]
not sure the meaning of c_train returned by sess.run()
I see open_spiel uses a test dataset to check the training accuracy 
https://github.com/ed2k/streamlit-example/blob/master/bridge/train_osp.py#L121

**Comment by Muppet1** [comment]
Pretty sure it measures the amount the NN learned that epoch.   previously the values made sense and fell as the epochs went up.

Quick other question which may be related.  Previously when making data I didn't bother to check the format of the text files.  But this time I noticed unless in utf8 the binary translator fails.  I did then make sure the txt files were all utf8.

**Comment by ed2k** [comment]
seems the bug is here https://github.com/lorserker/ben/blob/main/scripts/training/bidding/bidding_binary.py#L22
should use np.float16 not np.uint8 as indicated in binfo_binary.py
try to generate using binfo_binary.py

**Comment by Muppet1** [comment]
great yes that looks very likely.

**Comment by Muppet1** [comment]
But actually is not the problem.

I can only get sensible values for ctrain by using a really old version of the binary converter and the trainer and not the ones currently on this github page.
