### ISSUE TITLE
Custom Deals

### ISSUE THREAD

**Issue by adajcw** [lorserker/ben#27]
Is there a way to use pre-dealt hands in an existing library instead of random hands?

**Comment by lorserker** [comment]
yes, but you would have to edit the code a bit.
change this line to your custom deal
https://github.com/lorserker/ben/blob/main/src/gameserver.py#L26

**Comment by adajcw** [comment]
Would it be useful to add an  AWS instance as an image on Amazon 3rd party market place for anyone who might want to launch on AWS?
