### ISSUE TITLE
AWS  image?

### ISSUE THREAD

**Issue by adajcw** [lorserker/ben#28]
Would it be useful to  publish an aws instance as an image on Amazon 3rd party market place for anyone interested in spinning up on AWS?

**Comment by lorserker** [comment]
yes, that would be very useful!

**Comment by michael60045** [comment]
I have added an aws instance of the game engine for bridge as an image in the Amazon AWS Community AMIs for anyone interested in spinning up on AWS.   Here are the instructions:

Search for this AMI name in Amazon AWS Community AMIs:
Public_Ben_Bot_V1.2

Launch Public_Ben_Bot_V1.2 Amazon AMI with these settings:
Instance type is t2.large with 8gb memory, see Note (1)
Enable a public ip
open ports 8080 and 4443

Start bot:
ssh into instance as ubuntu user and
run these command while in home directory of home/ubuntu:

sh kill.sh
source start_ben_bot_screens.sh

Play bot:
Go to this url in any browser to play:
http://your_aws_instance_public_ip_address:8080/home


see Note (1)
I used the t2.large 8gb instance and allocated 4gb to swap memory.
Amazon costs to run a t2.large EC2 instance is about $2 per day.

**Comment by ThorvaldAagaard** [comment]
@michael60045 My AWS account has expired, and I don't think I am ever gone use it again.
Will you add some images so we can put your description in a readme file?

**Comment by michael60045** [comment]
Please clarify, the image is available in the Amazon AWS Community AMIs with the name "Public_Ben_Bot_V1.2".

**Comment by ThorvaldAagaard** [comment]
Ok, I assume the your description above is enough for people with AWS instances to run it. I was looking for some fine pictures (images) showing how to do it :-)

I assume it hasn't been updated since.

**Comment by ThorvaldAagaard** [comment]
Added to readme
