### ISSUE TITLE
Building on Apple silicon

### ISSUE THREAD

**Issue by suemanning** [lorserker/ben#31]
I have managed to build on for the M1 chip, here are my instructions.  It is tricky because many of the versions have to match, particularly numpy, grpcio, and tensorflow.  I am uncertain how easy it will be to move forward as versions change.

I used these links to help me:
https://developer.apple.com/metal/tensorflow-plugin/
https://developer.apple.com/forums/thread/702851  (see last post!)

If there are problems let me know and I'll try to fix them, or help you
[BenOnM1.txt](https://github.com/lorserker/ben/files/10071332/BenOnM1.txt)
[conda_setup.sh.zip](https://github.com/lorserker/ben/files/10071349/conda_setup.sh.zip)

**Comment by lorserker** [comment]
@suemanning very nice! thanks a lot for this!

**Comment by suemanning** [comment]
You are most welcome, thank YOU for writing the robot.
//sue

**Comment by suemanning** [comment]
BY THE WAY this does not work for training--additional code changes are needed, stay tuned....
