### ISSUE TITLE
Splinters don't seem to work

### ISSUE THREAD

**Issue by johny-b** [lorserker/ben#32]
Hi, I've noticed that the default model bids splinters, but responds to them as if they were natural balanced bids.

Or maybe I'm doing something wrong?

```
from nn.models import Models                                                    
from bots import BotBid                                                         
                                                                                
models = Models.load('../models')                                               
                                                                                
def full_auction(n, s):                                                         
    auction = []                                                                
                                                                                
    current_hand = n                                                            
    while len(auction) < 4 or set(auction[-3:]) != {'PASS'}:                    
        bot_bid = BotBid([False, False], current_hand, models)                  
        bid = bot_bid.bid(auction).bid                                          
        auction.append(bid)                                                     
        auction.append('PASS')                                                  
                                                                                
        current_hand = s if current_hand == n else n                            
                                                                                
    return auction
                                                                                
n = 'AK2.QJ543.A.5432'                                                          
s = 'D43.AK62.KD542.6'                                                          
                                                                                
print(full_auction(n, s))
```

returns `['1H', 'PASS', '4C', 'PASS', '5C', 'PASS', 'PASS', 'PASS']`

If we change `n` to `n = 'AK2.QJ543.A54.32'`, we get  `['1H', 'PASS', '4C', 'PASS', 'PASS', 'PASS']`

**Comment by johny-b** [comment]
OK, this isn't a thing when I use the `Bidding through an entire auction for all four hands` example from https://github.com/lorserker/ben/blob/main/src/examples/Bidding.ipynb.

What am I doing wrong? I just wanted a two-side-only bidding :)

**Comment by lorserker** [comment]
hi @johny-b 
the reason it doesn't work in your example is that you re-create the bot on every iteration of the while loop.
you need to create the bot one before the auction starts and then progressively go through the auction without creating a new instance of the bot. this is because the bot needs to keep internal state.
in your example the bot doesn't answer correctly because it "forgot" that it opened 1H and only pays attention to the 4C.

**Comment by johny-b** [comment]
@lorserker Thank you, everything works now :)

**Comment by 7NT** [comment]
> you need to create the bot one before the auction starts and then progressively go through the auction without creating a new instance of the bot. this is because the bot needs to keep internal state.

Since I am trying to build a BidBot in my web API server.  Usually, I have 2 bots play against real players as a pair.
Is it possible I can keep these bots' internal states during bidding in a web API server?

(Just started learning Python...)

**Comment by lorserker** [comment]
@7NT yes, it would be possible to do that.
but probably easier and better to make the service stateless (i.e for each request pass the entire bidding/play history)
