### ISSUE TITLE
seems the bot does not understand cuebid

### ISSUE THREAD

**Issue by 7NT** [lorserker/ben#37]
![Screenshot 2023-06-19 at 10 30 59 AM](https://github.com/lorserker/ben/assets/4128389/213bad9e-9135-44d3-b4fe-bf220dbcfb54)

The auctions are: 
auction = ['PAD_START','PAD_START','1H','PASS','1N','2S','3S','PASS'] 

North holds:
hand = 'Q74.9.KT95.A8742'

Clearly, the 3S by south over 2S is a cuebid, but what is the 4S raised by North?

Below is the code you can test it:

> import os
> #os.chdir('..')
> 
> from nn.models import Models
> from bots import BotBid
> from bidding import bidding
> from util import hand_to_str
> from deck52 import random_deal
> 
> models = Models.load('../models')   # loading neural networks
> 
> //# East deals, EW vulnerable.
> vuln_ns, vuln_ew = True, True
> 
> //# you sit North and hold:
> hand = 'Q74.9.KT95.A8742'
> 
> //# the auction goes:
> //# (a few words about 'PAD_START':
> //# the auction is padded to dealer North
> //# if North is not dealer, than we have to put in a 'PAD_START' for every seat that was skipped
> //# if East deals we have one pad (because North is skipped)
> //# if South deals we have two pads (because North and East are skipped)
> //# etc.)
> auction = ['PAD_START','PAD_START','1H','PASS','1N','2S','3S','PASS'] 
> 
> //# what's your bid?
> 
> bot_bid = BotBid([vuln_ns, vuln_ew], hand, models)
> 
> bid = bot_bid.bid(auction).bid
> 
> print(auction)
> print(bid)

**Comment by 7NT** [comment]
seems to me that North ignored that 2S bid by East

**Comment by lorserker** [comment]
what is strange is that North "knows" that East has long spades and South is short. Also South "knows" that North doesn't have length in spades. Still they end up playing 4S :)
That is not good at all

**Comment by 7NT** [comment]
I would try to check the combined length of the contract suit before the PASS.

If the length is  < 7, then select the next bid from bid.to_dict()['candidates']

Will test if this approach works

**Comment by lorserker** [comment]
@7NT I think that's a good idea. Thanks!

**Comment by 7NT** [comment]
I made a few steps to check if it's a (direct) cuebid before returning the BotBid.bid

If yes, then try to fixCueBid:

`if isCueBid(auctions, bid.bid) == True:  
        if (fixCueBid(bid)) == None:
            dummy_i = (decl_i+2) % 4
            strain_0 = bidding.get_strain_i(bid.bid)
            hands = bid.samples[0].split()
            decl_shdc = list(
                map(lambda x: len(x), hands[decl_i].split('.')))
            dummy_shdc = list(
                map(lambda x: len(x), hands[dummy_i].split('.')))
            dd_shdc = list(map(lambda x, y: x+y, decl_shdc, dummy_shdc))

            dummy_cards = hands[dummy_i].split('.')[strain_0-1]
            if hasStopper(dummy_cards):
                bid.bid = f'{level}N'
            elif (strain_i == 1):  # S
                suit_i = longSHDC(strain_i, dd_shdc)
                if suit_i > strain_i:
                    level += 1

                suit = ['N', 'S', 'H', 'D', 'C'][suit_i]
                bid.bid = f'{level}{suit}'

    return str(bid.bid)
`

I connected your bot to my online bridge site and join our daily tourneys as a pair (gg_2o1 and bb_2o1), results are not good :(

look at these biddings below:
![Screenshot 2023-06-26 at 3 54 20 PM](https://github.com/lorserker/ben/assets/4128389/594762b8-8bf1-4f83-be6b-ff1b106f009b)

![Screenshot 2023-06-22 at 3 06 31 PM](https://github.com/lorserker/ben/assets/4128389/792d6f00-600b-42da-9918-dd2b98c5e91b)

![Screenshot 2023-06-22 at 1 07 42 PM](https://github.com/lorserker/ben/assets/4128389/acefb25b-e422-4353-8eb0-14f3c2391d44)

![Screenshot 2023-06-19 at 10 30 59 AM](https://github.com/lorserker/ben/assets/4128389/0d29cb76-6230-42ac-a91d-405c514a3359)

**Comment by lorserker** [comment]
@7NT the bidding is too bad. it looks like there is something wrong.

to me it looks like the state of the bidding is not kept and only the last round is remembered. for example in the first board North makes a takeout double and then over 1NT it bids 2C stayman because it forgot its previous bid and thinks that partner opened 1NT.

Others have run into this problem, please take a look at this issue https://github.com/lorserker/ben/issues/32
If that doesn't solve it let me know if you need more help with the integration.

**Comment by 7NT** [comment]
haha

That makes sense, I will try "Bidding through an entire auction for all four hands" and will keep you updated...
