### ISSUE TITLE
Penalty double of a cuebid is passed out

### ISSUE THREAD

**Issue by lorserker** [lorserker/ben#39]
https://play.intobridge.com/hand?lin=pn|UnluckyHuman,Ben,Ben,Ben|md|3ST52HAJDQ8652CT75,SQ874HK3DKT7CK963,SAK963HQT65DAJ9C4,SJH98742D43CAQJ82|ah|Board%209|mb|1S|mb|p|mb|2S|mb|p|mb|4C|mb|d|mb|p|mb|p|mb|p|pc|D4|mc|0|sv|e|

the 4C cuebid is doubled by East, then both South and North pass and 4CX ends up being the contract?!!

(possibly this bug is related to this bug https://github.com/lorserker/ben/issues/37)

**Comment by lorserker** [comment]
this was passed out because none of the other candidates reached the simulation threshold.
do you remember which bid the simulation selected?

**Comment by ThorvaldAagaard** [comment]
It selected 4♠ that had the best expected score.

**Comment by ThorvaldAagaard** [comment]
Adding som e logic in the pass-out situation seems to have solved this
![image](https://github.com/lorserker/ben/assets/10560652/884cdb7a-248b-450c-8ce3-95068fa9a218)
