### ISSUE TITLE
Changes in viz.html in directory frontend

### ISSUE THREAD

**Issue by ThorvaldAagaard** [lorserker/ben#43]
I have some changes in viz.html, but not sure how to create a pull request, so for now I have just created a fork.

The changes are as follows
1: Removed the reference to log.js as that is only used in demo
2: Removed cards, so no cards will be presented id there is an error
3: Updated onreadystate to check the status before handling data, and included error handling
4: added handling of the 2 first buttons on the screen

I am not sure what the intention with the button btn-start-play is, so for now it just jumps to start.

The updated file can be seen at
https://github.com/ThorvaldAagaard/ben/blob/main/src/frontend/viz.html

**Comment by lorserker** [comment]
@ThorvaldAagaard thanks!
I think that you can make a pull-request from your fork

**Comment by ThorvaldAagaard** [comment]
I have created a pull request, including most of the fixes I have made. Let me know if there is anything in the process of making changes, that I can do better.

**Comment by lorserker** [comment]
@ThorvaldAagaard thanks!

**Comment by ThorvaldAagaard** [comment]
Solved in pull request #44
