### ISSUE TITLE
Error in Bidding_Binary.py

### ISSUE THREAD

**Issue by ThorvaldAagaard** [lorserker/ben#49]
I am no expert on python, but 
![image](https://github.com/lorserker/ben/assets/10560652/32a44221-529f-4d92-85c5-4383991057c0)
is only updating 1 in 10.000 deals as training

And when you look at it will you add a note why you are using 32 as number of cards?
![image](https://github.com/lorserker/ben/assets/10560652/8ca61692-e94b-4adf-bf0e-329bf5cc039b)

Reading the code it seems you are grouping cards from 7-2 in one group, and that seems like a good idea, but I think it is very few bidding systems that adds value to 8 and 9, so why not reduce the deck to 24?

**Comment by lorserker** [comment]
yes, the indentation looks wrong.

32 is quite arbitrary. for bidding it could be less, for play it probably should be more :)

**Comment by ThorvaldAagaard** [comment]
Solved in #57
