### ISSUE TITLE
Passing a pbn file to gameserver.py

### ISSUE THREAD

**Issue by drk1806** [lorserker/ben#54]
trying this with command,
python gameserver.py --boards f2_nr.pbn

and getting this error
![for_ben_sup](https://github.com/lorserker/ben/assets/138628736/c2ec8b27-3c7c-4105-b171-a927e3da2808)

**Comment by ThorvaldAagaard** [comment]
Seems not to be related to the PBN-file.
Looking more like the configuration is not read correctly.

Where is default.conf placed?

**Comment by drk1806** [comment]
in miniconada3\envs\ben-main\src\config.

**Comment by drk1806** [comment]
Here is a bigger screenshot.
![for_ben_sup1](https://github.com/lorserker/ben/assets/138628736/0e89957a-b285-4cce-b638-71c85f2893f4)

**Comment by ThorvaldAagaard** [comment]
Show me the content of default.conf

**Comment by drk1806** [comment]
[models]
include_system = False

[bidding]
bidder = models/gib21_model/gib21-1000000
info = models/gib21_info_model/gib21_info-500000
search_threshold = 0.1

[lead]
lead = models/lead_model_b/lead-1000000

[eval]
lead_single_dummy = models/lr3_model/lr3-1000000

[cardplay]
lefty = models/lefty_model/lefty-1000000
dummy = models/dummy_model/dummy-920000
righty = models/righty_model/righty-1000000
decl = models/decl_model/decl-1000000

[sampling]
lead_accept_threshold = 0.01
bidding_threshold_sampling = 0.1
play_accept_threshold = 0.03
bid_accept_play_threshold = 0.05
sample_hands_auction = 64

**Comment by ThorvaldAagaard** [comment]
Have you activated the environment?

**Comment by drk1806** [comment]
I think so, the conda activate command puts me back in command prompt as image shows. Is that right?
![for_ben_sup2](https://github.com/lorserker/ben/assets/138628736/7f78ffa6-994d-4e59-bb3d-0c1afae9295f)

**Comment by drk1806** [comment]
Oops. Working now. Thanks for your help.
