### ISSUE TITLE
Installing Ben on Mac OS gives error

### ISSUE THREAD

**Issue by drk1806** [lorserker/ben#55]
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0)
ERROR: No matching distribution found for tensorflow==1.15
Ventura 13.4.1 on a Mac mini M1

**Comment by drk1806** [comment]
This happens during conda_setup.sh script.

**Comment by lorserker** [comment]
@drk1806 i don't have a mac to try it.
some people write here that they managed to get it work: https://github.com/lorserker/ben/issues/33
let me know if the solutions described there don't work for you and we'll try to find a way

**Comment by lorserker** [comment]
i am closing the issue. please write following questions on the linked one so we have mac setup related things in one place
https://github.com/lorserker/ben/issues/33

**Comment by drk1806** [comment]
Thanks.

I tried to use the solution from channel but did not work. Updated the
channel.

**Comment by drk1806** [comment]
I know you have a new build you are working on , will that have the most
recent version of tensorflow. If that is the case, I can hold off trying to
install ben on my mac mini. When is that build supposed to be out?

Jay
