### ISSUE TITLE
Thought on training

### ISSUE THREAD

**Issue by Muppet1** [lorserker/ben#56]
Not a bug.

Currently we train on a lot of hands which seems like a good idea.  One possible problem down the line when we are trying to make better nets is that it will see a lot of opening bids and very quickly these become close to 1.  My suggestion is to only train on a few opening bids relatively and once a certain threshold is reached skip them.

when I thought of this a while back I also realised it would work for chess.  I jumped onto the stockfish server and oddly someone had thought of it one month before so I may have read that and forgotten I guess.   Anyway skipping some opening moves improved even stockfish a bit, and I think the gains in bridge would be more than chess as there are fewer openings.

Obviously I have no clue how to actually do this so I raise it as a thought for the future.

**Comment by lorserker** [comment]
@Muppet1 thanks! i like the idea

**Comment by ThorvaldAagaard** [comment]
I have implemented bidding_coverage.py, that limits a given bidding sequence to 10. I am not sure 10 is the right number, but the results seems fine, and the current model is trained with this option.

So I will close this
