### ISSUE TITLE
can add " save and load game state " function?

### ISSUE THREAD

**Issue by seebrand** [lorserker/ben#69]
The demo site works well , great engine !  Can it modified to add  functions as   user log in /log out/,  save and load game state  for  recording user playing state ? that sounds a real game .   thanks a lot.

**Comment by lorserker** [comment]
@seebrand yes, i think that the things you mentioned are possible to implement

**Comment by ThorvaldAagaard** [comment]
@seebrand Are you thinking of running this on your own pc or on a server?

Currently all plays are stored for replay, but to see how we can achieve your goal a longer description would be needed.

**Comment by seebrand** [comment]
running on server. hope:
1.system supports multi user login
2. PK contest between 2 players. 
3. for convenience,  it needs saving and restoring user's every action,  such as bidding, card playing to deal with network disconnection and other emergency.  you can login and continue playing in another time.

**Comment by ThorvaldAagaard** [comment]
It will cost to run a server, and there must be developed a nice UI. I know IntoBridge is replacing BEN, but is there something else than what you can do on IntoBridge you are looking for?

**Comment by seebrand** [comment]
hope realize more func like intoBridge  :)

**Comment by ThorvaldAagaard** [comment]
I have started a server on http://ben.aalborgdata.dk:8080/home

But login, saving state and competitions are currently not on my plans
