### ISSUE TITLE
do we plan to share `ben` model in huggingface.co ?

### ISSUE THREAD

**Issue by larrycai** [lorserker/ben#73]
https://huggingface.co/ is the de-facto hub for models like github to code.

could be interesting to see whether it can be popular there if it is released? 

related with #52, the model itself can be released separately from ben (engine)

**Comment by ThorvaldAagaard** [comment]
You are welcome to give it a try.

we have many different models and is working on a new for the UCBC. What is needed?

**Comment by lorserker** [comment]
@larrycai go for it! :)

**Comment by larrycai** [comment]
@ThorvaldAagaard or @lorserker , you can be the owner to create the org like "TheBen" ;-), then I more prefer to join to contribute. (one famous org there is https://huggingface.co/TheBloke )

* TheBen
* TheBenAI
* BenAI
* TheBridgeAI
* ..

Someone start to create one repo (one model), then I man learn how to manage the repo in huggingface with examples.

**Comment by ThorvaldAagaard** [comment]
I have created an organization on huggingface.co TheBen was taken so I ended up with: AIBridgeEngine

You can join using this link

https://huggingface.co/organizations/AIBridgeEngine/share/NsNyVpHrebERmsdGTYUiFXyIwjWlhyarIT
