### ISSUE TITLE
At Tutorial: CardByCardAnalysis

### ISSUE THREAD

**Issue by eherrera1971** [lorserker/ben#77]
Hi
I am getting this error:
![image](https://github.com/lorserker/ben/assets/31047459/e7fedfc2-52e1-4fae-9058-526f5edb118a)

What I am doing wrong?
Thanks,
Eduardo

**Comment by ThorvaldAagaard** [comment]
Probably me not committing a change I made yesterday - remove 0.1, in the line in error. This parameter is now being read from the configuration file.

**Comment by ThorvaldAagaard** [comment]
I have committed an updated version also
