### ISSUE TITLE
(idea discussion) ben project structure improvement

### ISSUE THREAD

**Issue by larrycai** [lorserker/ben#79]
# Background

It is just discussion for possible changes, it will not be implemented now. Record some experience and trials to see possible future.

So far it is one `ben` project contains everything, bit tricky to refactor and check/use partly.

* `ben-model` for training models only, the models (result) can be stored in huggingface.co, tried in #76
* `ben-lite`/`ben-engine` for AI bridge library, it can be used to pypi package to be reused in other project (it will load ben-models)
* `ben` ( `ben-ui`) for ben's sandbox web application, uses `ben-lite` for one web application

Then each part can be easily grows and invite more contributors to join

# Use cases

* Use just ben engine models to write bridge articles (use model or compare this model with other bridge software) to analysis the bidding, opening leads, playing ...
* improve the ben-ui separately as a game without good knowledge of bridge, they just need to know the API provided by `ben-lite`

**Comment by lorserker** [comment]
@larrycai yes, this seems like a good idea.

**Comment by larrycai** [comment]
Busy this week, and I did some checking (with my limited python knowledge)

## python standard project

If we want to change later, we need to 

* better to follow python project structure (`src/ben/`)
* module dependance needs to be updated (`from .bidding import bidding`), see sample: https://github.com/larrycai/ben-lite/commit/b3049ccfc55856db61adae328adf11a8def43f63

see i tried in https://github.com/larrycai/ben-lite (it is just trial)

## jupyter notebook

if it is separated, then it can work like https://github.com/larrycai/ben-lite/blob/main/Leading_for_3NT.ipynb (just prepared the env), it mostly looks like below in non-root jupyter env (see also redeal issue https://github.com/anntzer/redeal/issues/36)

````
!pip install --upgrade git+https://github.com/larrycai/ben-lite # install ben pure python package, just for demo, DON'T rely on it.
!pip install git+https://github.com/larrycai/redeal # install redeal without dds depend
!git clone https://github.com/larrycai/dds-so.git  # clone and get libdds.so
!pip show redeal
````

AI/ML data engineer with bridge knowledge can just use jupyter notebook to compare

**Comment by ThorvaldAagaard** [comment]
I think we should create small installables, so if you just want to analyze a deal in jupyter you don't need to install the modules for training etc, But should we have different repositories, or can we manage to have it all in one? There are some reuse, and when developing it is an advantage to have al together.

But I think it is a good idea to have all that is distributed in /src and then have subdirectories for the different modules

**Comment by larrycai** [comment]
yes, this is exactly what I tried above ;-)

* https://github.com/larrycai/ben-lite is just source code, which later can be `pip install ben`, how many src inside can be discussed
* modules are hosted in huggingface.co, it is downloaded during usage, it is what we discussed in #76

**Comment by larrycai** [comment]
Now it is a complete demo how to use AI ben engine to compare with [readel](https://github.com/anntzer/redeal) solution (check book [Winning Notrump Lead](https://www.amazon.se/Winning-Notrump-Leads-David-Bird/dp/1554947596)), I use hand 3, Chapter 1 to compare

see https://github.com/larrycai/ben-lite/blob/main/Leading_for_3NT_Colab.ipynb 

You can load it in [colab](https://colab.research.google.com/) and rerun all to check, redeal takes 3 minutes.

@lorserker , I am not good at checking the result, I more focus the env

let me know if someone else make it works.

**Comment by larrycai** [comment]
> I think we should create small installables, so if you just want to analyze a deal in jupyter you don't need to install the modules for training etc, But should we have different repositories, or can we manage to have it all in one? There are some reuse, and when developing it is an advantage to have al together.
> 
> But I think it is a good idea to have all that is distributed in /src and then have subdirectories for the different modules

yes, the training part can be released with models (`ben-models`), or as first step, put into one src package.

**Comment by ThorvaldAagaard** [comment]
Very interesting.

So I jumped to Colab, and entered 
https://colab.research.google.com/github/larrycai/ben-lite/blob/main/Leading_for_3NT_Colab.ipynb#

Now when I try to run step 3 (the solution from rdeal) I get this error
![image](https://github.com/lorserker/ben/assets/10560652/be418649-c13e-489d-843b-a732465f8cd9)
but it looks like rdeal is installed ok in step 1 and 2

Loading all models worked fine, but again, when I tried to execute BEN, I got an error
![image](https://github.com/lorserker/ben/assets/10560652/dc6b9af4-93a2-40be-9dc9-f77bfda58f08)

**Comment by larrycai** [comment]
Oops, little bit weird for jupyternotebook, some old commands exist before summit.

I removed `--user`, it works again now. I verified  from menu `Runtime`-> `Restart and run all`.

> updated https://github.com/larrycai/ben-lite/blob/main/Leading_for_3NT_Colab.ipynb

**Comment by larrycai** [comment]
omg, I made so many mistakes there, fixed there. I also reported once case https://github.com/anntzer/redeal/issues/37 to see whether we can use redeal for the better format (small thing)

I had all the things now for the discussion.

closed now, when we really need to do this, I can contribute to verify.

**Comment by ThorvaldAagaard** [comment]
When sampling for the lead I have added a new column, that gives a score from 0-1 about how close the bidding is to BEN's engine - but the score is just the bid with the lowest score for all players - I am thinking about how that can be improved.

You should update the text here:
![image](https://github.com/lorserker/ben/assets/10560652/09aa6894-769e-4238-922f-686a1a7020c5)

In this section:
![image](https://github.com/lorserker/ben/assets/10560652/5e5107b7-fecd-4663-b5e0-66ab058e67e8)

we should make some changes, so the relation between
bidding_id="AIBridgeEngine/Ben-3B-Bidding-v0.1"
and 
bidder = Bidder("", f'{folder}/bidding-100000')

So the user only will have to know the model name on HuggingFace.

My best idea for now is just to rename the model files on HuggingFace
