### ISSUE TITLE
Undeclared variables when running random games

### ISSUE THREAD

**Issue by ataylorappt** [lorserker/ben#82]
I am running random games in docker on linux on the main branch (b9361d3368a2536d66fc70f6d6e6be432fed8220).

In the `src/gameserver.py` line 156:
    `driver.set_deal(None, *rdeal, ns, ew, False)`

ns and ew are both undefined causing the below error:
    `NameError: name 'ns' is not defined`

**Comment by ThorvaldAagaard** [comment]
Fixed, ns and ew is moved to the configuration file and it was updated everywhere else in the file.
Thx for noticing
