### ISSUE TITLE
EPBot and paths error

### ISSUE THREAD

**Issue by ZiggerZZ** [lorserker/ben#86]
Is EPBot supposed to be working on Unix/Mac?

I'm seeing lines

```
if sys.platform == 'win32':
    EPBot_LIB = 'EPBot86'
elif sys.platform == 'darwin':
    EPBot_LIB = 'N/A'
else:
    EPBot_LIB = 'N/A'
```

in `BBA.py`.

Also, when I'm launching `table_manager_client.py`, I see 

```
Traceback (most recent call last):
  File "/root/ben/src/table_manager_client.py", line 763, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/ben/src/table_manager_client.py", line 727, in main
    models = Models.from_conf(configuration, base_path.replace(os.path.sep + "src",""))
  File "/root/ben/src/nn/models.py", line 48, in from_conf
    bidder_model=Bidder('bidder', os.path.join(base_path, conf['bidding']['bidder'])),
  File "/root/ben/src/nn/bidder.py", line 17, in __init__
    self.load_model()
  File "/root/ben/src/nn/bidder.py", line 34, in load_model
    saver = tf.compat.v1.train.import_meta_graph(self.model_path + '.meta')
  File "/root/ben/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1583, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/root/ben/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1599, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/root/ben/venv/lib/python3.10/site-packages/tensorflow/python/framework/meta_graph.py", line 611, in read_meta_graph_file
    raise IOError(f"File does not exist. Received: {filename}.")
OSError: File does not exist. Received: /root/ben/D:\github\ben\UCBC 2024\Models\bidding-3233000.meta.
```

So the path to `bidding-3233000.meta` is hardcoded to `D:\github\ben\UCBC 2024\Models\bidding-3233000.meta`. Can't it be a relative path, and also not Windows path?

**Comment by ThorvaldAagaard** [comment]
EPBot is not working on Unix/Mac

The module  BBA.py should not be loaded unless it is configured in the configuration file 

```
use_bba = True
```

The model file with an absolute path is because I have committed (unintentionally) a version with absolute paths.
I will fix this shortly.

We might need to have different config-files for the different platforms

**Comment by ZiggerZZ** [comment]
Are you sure it's not working? I was able to install `mono` for `pythonnet`.

So how am I supposed to launch `table_manager_client.py` with the correct config?

**Comment by ThorvaldAagaard** [comment]
I haven't tested it, so it might work :-)
I think there was an earlier issue on it, where I made sure it wasn't loaded unless needed, same for pythonnet

To load a config-file for the table manager:

```python table_manager_client.py --config <name of configuration file>```

it has these optional parameters:
```
    parser.add_argument("--host", type=validate_ip, default="127.0.0.1", help="IP for Table Manager")
    parser.add_argument("--port", type=int, default=2000, help="Port for Table Manager")
    parser.add_argument("--name", required=True, help="Name in Table Manager")
    parser.add_argument("--seat", required=True, help="Where to sit (North, East, South or West)")
    parser.add_argument("--config", default=f"{base_path}/config/default.conf", help="Filename for configuration")
    parser.add_argument("--biddingonly", type=bool, default=False, help="Only bid, no play")
    parser.add_argument("--verbose", type=bool, default=False, help="Output samples and other information during play")
```

**Comment by ZiggerZZ** [comment]
What is EPBot needed for? Will Unix/Mac version work without it?

**Comment by ThorvaldAagaard** [comment]
EPBot is from: https://sites.google.com/view/bbaenglish

It is the program we use for generating the training data loaded into the neural network.

So using EPBot i can test BEN's bidding without using the neural network

So it is only needed for testing

**Comment by ZiggerZZ** [comment]
Perhaps you can fix `default.conf` so it works for all platforms, and/or set `use_bba=False`? I'm confused on where I need to set `use_bba=False` to avoid the issue.

**Comment by ThorvaldAagaard** [comment]
use_bba is false.

I will download latest version and check it is OK on my Mac

**Comment by ZiggerZZ** [comment]
Since I'm getting `/root/ben/D:\github\ben\UCBC 2024\Models\bidding-3233000.meta` in the terminal (check the full log in the first message), I suppose it tries to load `bidder` on line 9 of `default.conf`.

**Comment by ThorvaldAagaard** [comment]
Try again. I only fixed it in gameserver last time

There should be no references to D:\github in the config files

**Comment by ThorvaldAagaard** [comment]
I don't think the protocol implementation has been changed.
Can you send me the log - it could be the sampling that is causing problems.

But first start ```table_manager_client.py``` with --verbose True as that will give a lot more interesting log

**Comment by ZiggerZZ** [comment]
I ran it with `--verbose` and got the following issue:

```
Traceback (most recent call last):
  File "/root/ben/src/table_manager_client.py", line 772, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/ben/src/table_manager_client.py", line 756, in main
    await client.run(biddingonly)
  File "/root/ben/src/table_manager_client.py", line 107, in run
    await self.play(auction, opening_lead52)
  File "/root/ben/src/table_manager_client.py", line 325, in play
    print(f"{candidate.card} Expected Score: {str(int(candidate.expected_score)).ljust(5)} Tricks (DD) {candidate.expected_tricks_dd:.2f} #Insta_score {candidate.insta_score:.4f}")
AttributeError: 'CandidateCard' object has no attribute 'expected_score'. Did you mean: 'expected_score_dd'?
```

Without digging much more I opened #88, hopefully it fixes the issue.

**Comment by ZiggerZZ** [comment]
The rest is fine so far.

**Comment by ThorvaldAagaard** [comment]
Closing as all seems to be fine now.
