### ISSUE TITLE
crazy bidding

### ISSUE THREAD

**Issue by seebrand** [lorserker/ben#87]
In test bidding for some examples by using UCBC2024.conf  models, crzay bidding  happended !
hands = ['AK64.8642.Q32.Q6','9.QT973.AT5.KJ94','QT532.J5.KJ974.7','J87.AK.86.AT8532'] 
West is dealer, open normal 1c.  when bidding by Ben complely automatic, the bidding can reach normal EW 5C. the bidding sequence is ['1C', 'PASS', '1H', 'PASS', '2C', 'PASS', '5C', 'PASS', 'PASS', 'PASS'].
But when i replace south first bidding by '1S' , bidding by NS go mad !
['1C', 'PASS', '1H', '1S', '2C', '3C', '3N', 'PASS', 'PASS', 'X', 'PASS', '4S', 'X', 'PASS', '5C', 'PASS', 'PASS', 'X', 'PASS', '5D', 'X', '6S', 'X', '7S', 'X', 'PASS', 'PASS', 'PASS']
Following is my code : 
models = Models.from_conf(conf.load('../Conf/UCBC2024.conf'),'..')   # loading neural networks
sampler = Sample.from_conf(conf.load('../Conf/UCBC2024.conf'), False)  # Load sampling strategies
bidder_bots = [BotBid([False, False], hand, models, sampler, False) for hand in hands]
auction = []
turn_i = 3  # whose turn is it to bid
step = 0
while not bidding.auction_over(auction):
     bid = bidder_bots[turn_i].bid(auction)
     # if step== 1:
     #     bid.bid='X'
     if step== 3:
         bid.bid='1S'
     auction.append(bid.bid)
     turn_i = (turn_i + 1) % 4  # next player's turn
     step += 1
print('My bidding is: ',auction)

**Comment by seebrand** [comment]
thanks a lot . when setting auction = ['PAD_START','PAD_START','PAD_START'] ,  results  in 5CX, that's ok .

**Comment by seebrand** [comment]
when set aution= [] and logging = true,results in 7SX:

sample_cards_vec generating 5000
n_samples 1371 matching bidding info
sample_cards_auction, nsteps= 6
NS:  1.0 EW:  99.0 Auction:  ['1C', 'PASS', '1H', '1S', '2C', '3C', '3N', 'PASS', 'PASS', 'X', 'PASS', '4S', 'X', 'PASS', '5C', 'PASS', 'PASS', 'X', 'PASS', '5D', 'X', '6S']
Player:  S Hand:  9.QT9xx.ATx.KJ9x
HCP:  [10.54 12.05  7.66]
Shape:  [5.09 2.81 3.29 1.73 2.22 1.95 3.16 5.79 4.21 3.36 3.78 1.6 ]
sample_cards_vec generating 5000
n_samples 1371 matching bidding info
sample_cards_auction, nsteps= 6
NS:  1.0 EW:  99.0 Auction:  ['1C', 'PASS', '1H', '1S', '2C', '3C', '3N', 'PASS', 'PASS', 'X', 'PASS', '4S', 'X', 'PASS', '5C', 'PASS', 'PASS', 'X', 'PASS', '5D', 'X', '6S', 'X']
Player:  W Hand:  QTxxx.Jx.KJ9xx.x
HCP:  [12.08  9.35 11.28]
Shape:  [2.04 2.38 2.68 6.01 3.54 4.24 3.1  2.   2.38 4.6  2.45 3.55]
sample_cards_vec generating 5000
n_samples 1399 matching bidding info
sample_cards_auction, nsteps= 7
NS:  1.0 EW:  99.0 Auction:  ['1C', 'PASS', '1H', '1S', '2C', '3C', '3N', 'PASS', 'PASS', 'X', 'PASS', '4S', 'X', 'PASS', '5C', 'PASS', 'PASS', 'X', 'PASS', '5D', 'X', '6S', 'X', '7S']

**Comment by ThorvaldAagaard** [comment]
Can you recreate this in latest version?

**Comment by ThorvaldAagaard** [comment]
Closing as no reponse
