### ISSUE TITLE
analysis UI bug: last trick assigned to wrong side

### ISSUE THREAD

**Issue by lorserker** [lorserker/ben#9]
in the https://lorserker.github.io/ben/demo/viz.html?deal=1 playback if you click next card through out the hand the last trick is scored as going to the defense N/S instead of to the E/W that won it.

seems to be related to the fact that the trick count is not updated after all four cards have been played (it's only updated when the next trick starts)

**Comment by lorserker** [comment]
postponing work on this bug

**Comment by ThorvaldAagaard** [comment]
As far as I can see you have trickWinners as 0-3, starting from North, and when you are on the last tricks you create the TricksTaken a bit different in viz.js

![image](https://github.com/lorserker/ben/assets/10560652/e9ebb3f7-f89d-4de8-8ea3-6d5bf2dc0bf8)

Compared to
![image](https://github.com/lorserker/ben/assets/10560652/50521b61-710f-45bb-8c6a-6b968f20307a)

So just moving the +1 from ew to ns should fix the problem. 

Remember viz.js is included twice in the repository.

**Comment by lorserker** [comment]
thanks @ThorvaldAagaard
