### ISSUE TITLE
Unable to generate data with GiB

### ISSUE THREAD

**Issue by bookchris** [lorserker/ben#95]
I've been trying to follow the GiB data generation steps here:
https://github.com/lorserker/ben/blob/main/scripts/data/gib/README.md

But the client I installed (from the link provided) doesn't like the 'a' argument:

```
bridge.exe a < input.gib > output.txt
```

Is that the right command syntax?  I can't find any command-line documentation for this.

**Comment by ThorvaldAagaard** [comment]
If you have installed GIB following the link in the description the syntax should be right.

But try  first just writing

```bridge```
and verify you are in the right directory.

Response should be like this:
![image](https://github.com/lorserker/ben/assets/10560652/7fd93e42-599e-4b73-8d60-14ec79151a1e)

Now make sure the input file is in the right location and if still a bad response paste the response in this issue, then I might be able to detect the problem.

This was the output for me
![image](https://github.com/lorserker/ben/assets/10560652/b1807c05-7680-4c46-8a2a-71c5e28bab93)

note that the message: ```can't open a``` is expected

**Comment by bookchris** [comment]
Ah, thanks.  I think it was still using an older version.  Got it working now!
