### ISSUE TITLE
A bug in the play of the demo boards

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#96]
When I checked the demo bords from 
https://lorserker.github.io/ben/demo/demo.html
the card which is led is not part of the hand which leads.
For example in board 1 North leads 7h but does not have 7h.
In fact no of the cards belongs to the correct hand. The first trick goes (N: 7h, E: 2h, S: Kc, W: 7c
![Screenshot Board1](https://github.com/lorserker/ben/assets/33804161/2396699b-1def-45a5-a175-397c43aaacce)

I checked the other boards - same issue

regards
Andreas

**Comment by ThorvaldAagaard** [comment]
You can try http://ben.aalborgdata.dk:8080/
The demo deals are pretty old, and I haven't had time to create new ones.

**Comment by ThePokerDude** [comment]
Thanks for the link.

**Comment by ThorvaldAagaard** [comment]
The bug in the Demo boards are fixed a next commit. Thank you for reporting. (I still need to update the demo boards as we are showing more internal information for the deals now.

**Comment by ThorvaldAagaard** [comment]
Fixed now
